version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Europe/Berlin"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    groups:
      minor-patch-upgrades:
        # Dependabot prefers longest match over evaluation order.
        # Make sure you add all more specific patterns of groups tackling major updates
        # (otherwise their minor/patch updates will be grouped in isolation).
        patterns:
          - "*"
          - "*opentelemetry*"
          - "tonic*"
          - "prost*"
          - "utoipa*"
          - "tracing*"
          - "axum*"
          - "tower*"
        update-types:
          - "minor"
          - "patch"
      opentelemetry:
        patterns:
          - "*opentelemetry*"
        update-types:
          - "major"
      tonic-prost:
        patterns:
          - "tonic*"
          - "prost*"
        update-types:
          - "major"
      utoipa:
        patterns:
          - "utoipa*"
        update-types:
          - "major"
      tracing:
        patterns:
          - "tracing*"
        update-types:
          - "major"
      axum-tower:
        patterns:
          - "axum*"
          - "tower*"
        update-types:
          - "major"
  - package-ecosystem: "rust-toolchain" 
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Europe/Berlin"
